### ISSUE TITLE
All templates suddenly lost (on multiple disconnected computers!)

### ISSUE THREAD

**Issue by arongombas** [gorgias/gorgias-chrome#104]
This plugin saves us a lot of typing when communicating. We have been using it for about a month, and it worked like a charm.

Yesterday, suddenly, all my 20-25 templates disappeared. I can't auto-complete, and when I open the config dialog it shows zero templates. It is really frustrating.

Environment: Ubuntu, Chrome, Gmail

I initially thought that I may have deleted them accidentally, but I have another laptop at home, also installed with the plugin and just the same day the templates disappeared on that as well?!! Gorgias is NOT auto-synched between them, but the general syncing (bookmarks, plugins, etc.) via Google login is turned on (never caused any problem).

Is this a general problem that may be caused by an auto-upgrade of Chrome or the Gorgias plugin?

**Comment by xarg** [comment]
@arongombas Sorry about this, but don't worry, your templates are not lost.

I have migrated from webSQL to chrome.storage in the latest update so it maybe related. Could first check that the version you are using is 2.5.5 and if that's the case could you click on inspect view and see if there are any errors here (might need to enable developer mode first):

![inspect-views](https://cloud.githubusercontent.com/assets/94721/6481054/934af4a4-c262-11e4-9543-9e4039264fdd.png)

**Comment by arongombas** [comment]
It is 2.5.5, yes. (At least on my home laptop.)

In the console 2 warnings and 2 errors! These are the errors:

# One
 TypeError: Cannot read property 'subject' of undefined
    at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:59364:59
    at processQueue (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:33749:27)
    at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:33765:27
    at Scope.$eval (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:34961:28)
    at Scope.$digest (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:34777:31)
    at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:35000:26
    at completeOutstandingRequest (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:25465:10)
    at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:25845:7 undefined

# Two
https://app.getsentry.com/api/30379/store/?sentry_version=4&sentry_client=r…222.5.5%22%7D%2C%22event_id%22%3A%22b4ba63bbf36b4062b8e60b4abb0215fe%22%7D Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)

**Comment by xarg** [comment]
Thank you @arongombas I published an update just now 2.5.6 that should fix the issue. Usually it takes about 30m to 1h to update. Could you check back then and see if it works?

**Comment by arongombas** [comment]
Hmmm, after the previous comment I came to the office and on my work laptop the templates appeared again! AWESOME!

But, when I look at the "Extension" list, it still shows the 2.5.5 version number. WTF?

**Comment by xarg** [comment]
Have you updated your Settings in the extension on your work laptop? It might explain fixing the issue. I've put some more checks in the last update to make sure it works. It should have worked before and the only explanation I have is that Google Chrome Sync didn't work as expected.

Good to know it fixed your problem though.

**Comment by arongombas** [comment]
Honestly, I don't think I did anything related to Chrome or its extensions. Ubuntu will not invisibly upgrade the browser, but I don't know what Chrome does or doesn't do under the hood...

Anyway, now with this working again, I'm a happy camper.

**Comment by xarg** [comment]
Chrome Sync is a Google service which I use to save the Settings of the extension. One field was missing and it should have been there. Since it was not I blame Chrome Sync not doing it's job (connection issues, write conflicts, etc..), but really I should have put additional checks to make sure the variable is present.

Closing this for now and let me know if you have any other issues.
